app/Http/routes.php
<?php

$router->pattern('series_slug', '[A-Za-z-]+');
$router->pattern('person_slug', '[A-Za-z-]+');

$router->pattern('episode_number', '\d+');

Route::group(['middleware' => ['web']], function () {

    Route::auth();

    Route::group(['prefix' => 'api', 'middleware' => 'auth'], function(){

    	Route::resource('people', 'Api\PeopleController');
    	Route::resource('series', 'Api\SeriesController');
    	Route::resource('episodes', 'Api\EpisodeController');
    	Route::resource('art', 'Api\AlbumArtController');

    	Route::get('media/check', ['as' => 'media-check', 'uses' => 'Api\MediaController@check']);
    });

    Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function(){

    	Route::get('dashboard', ['as' => 'dashboard', 'uses' => 'Admin\DashboardController@index']);

    	Route::resource('series', 'Admin\SeriesController');

    	Route::resource('episodes', 'Admin\EpisodeController');

    	Route::resource('art', 'Admin\ArtController');

    	Route::resource('people', 'Admin\PeopleController');

    	Route::group(['prefix' => 'ajax'], function(){

    		Route::get('people/search/', 'Admin\AjaxController@peopleSearch');
    		Route::get('people/initial/', 'Admin\AjaxController@people');

    		Route::get('episode/related/search/', 'Admin\AjaxController@episodesSearch');
    		Route::get('episode/related/initial/', 'Admin\AjaxController@episodes');

    		Route::get('media/initial/', 'Admin\AjaxController@mediaInitial');
    		Route::get('media/check/', 'Admin\AjaxController@mediaCheck');

    		Route::post('art/upload/', 'Admin\ArtController@upload');
    	});

    });

    /**
     * Root routes.
     *
     * Routes that are attached to the /
     * - home
     * - latest
     * - admin shortcut
     */

    Route::get('admin', [
      'uses' => 'Frontend\RootController@admin'
    ]);

    Route::get('/', [
      'as' => 'home',
      'uses' => 'Frontend\RootController@home'
    ]);

    Route::get('/latest', [
      'as' => 'latest',
      'uses' => 'Frontend\RootController@latest'
    ]);

    /**
     * People routes.
     *
     * - people's full list
     * - a person's page
     */

    Route::get('/people/', [
      'as' => 'people',
      'uses' => 'Frontend\PeopleController@people'
    ]);

    Route::get('/person/{person_slug}/', [
      'as' => 'person',
      'uses' => 'Frontend\PeopleController@person'
    ]);

    /**
     * Episode routes.
     *
     * Most of these routes are functionally redirects.
     *
     * - /episode/{s}{n}; legacy format
     * - /e/{id}; shortcut format
     * - /{s}{n}; legacy shortcut format
     * - /{s}/{n}; new format (that everyone loves)
     */

    Route::get('/episode/{series_slug}{episode_number}', [
      'uses' => 'Frontend\EpisodesController@episodeLegacyRedirect'
    ]);

    Route::get('/e/{id}', [
      'uses' => 'Frontend\EpisodesController@episodeByIdRedirect'
    ]);

    Route::get('/{series_slug}{episode_number}/', [
      'uses' => 'Frontend\EpisodesController@episodeLegacyRedirect'
    ]);

    Route::get('/{series_slug}/{episode_number}/', [
      'as' => 'episode',
      'uses' => 'Frontend\EpisodesController@episode'
    ]);

    /**
     * Series routes.
     *
     * - series list
     * - single series (redirect)
     * - single series
     */

    Route::get('/series', [
      'as' => 'series-list',
      'uses' => 'Frontend\SeriesController@seriesList'
    ]);

    Route::get('/series/{series_slug}', [
      'as' => 'series',
      'uses' => 'Frontend\SeriesController@seriesSubslug'
    ]);

    Route::get('/{series_slug}/', [
      'as' => 'series',
      'uses' => 'Frontend\SeriesController@series'
    ]);

    Route::get('/master/feed', [
      'as' => 'master.feed',
      'uses' => 'Frontend\FeedsController@feedMaster'
    ]);

    /**
     * Route for series/feed.
     *
     * This route fetches the published episodes without fringes
     * of the specified episode.
     */
    Route::get('/{series_slug}/feed', [
      'as' => 'series.feed',
      'uses' => 'Frontend\FeedsController@feedGeneral'
    ]);

    /**
     * Route for series/feed/fringe.
     *
     * This route gets the latest episodes and their fringes if they are available,
     * and merges them into a single collection for the feed.
     *
     * TODO: fix this awful query mess
     * TODO: really, why haven't you fixed this yet?
     */
    Route::get('/{series_slug}/feed/fringe', [
      'as' => 'series.feed.fringe',
      'uses' => 'Frontend\FeedsController@feedFringe'
    ]);

});

app/Http/Controllers/Admin/SeriesController.php
<?php namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
// use Request;

class SeriesController extends Controller {

	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct()
	{
		$this->middleware('auth');
	}

	public function index() {
		$series = \App\Series::orderBy('name')->get();

		$array = ['series' => $series];
		return view('admin.series.index', $array);
	}

	public function show($id) {
		return redirect(route('admin.series.index'));
	}

	public function create() {
		return view('admin.series.create');
	}

	public function store(Request $request) {

		$fields = $request->except(['meta', 'art']);

		$series = \App\Series::create($fields);

		$meta = \App\SeriesMeta::create($request->input('meta'));

		$series->meta()->save($meta);

		$this->saveArt($series, $request);

		return redirect(route('admin.series.edit', $series->id))
				->with(['flash.message' => 'Series created!',
						'flash.level'	=> 'success']);
	}

	public function edit($id) {
		$series = \App\Series::with(['meta', 'art', 'hosts'])->findOrFail($id);

		$array = ['series' => $series];
		return view('admin.series.edit', $array);
	}

	public function update($id, Request $request) {

		$series = \App\Series::with(['meta', 'art'])->findOrFail($id);

		$fields = $request->except(['meta', 'art']);

		$series->update($fields);

		$series->meta()->update($request->input('meta'));

		$this->saveArt($series, $request);

		$this->saveHosts($series, $request);

		return redirect(route('admin.series.edit', $series->id))
			->with(['flash.message' => 'Series updated!',
					'flash.level'	=> 'success']);
	}

	private function saveHosts($series, $request) {
		$hosts = $request->input('people_default', []);
		$series->hosts()->sync($hosts);
	}

	private function saveArt($series, $request) {
		$art = $request->input('art_list', []);

		// force items in the array to be numeric - such that they are ids
		$filtered = array_filter($art, function($item){
			return is_numeric($item);
		});

		$series->art()->sync($filtered);
	}

	public function destroy($id) {
		$series = \App\Series::with('meta')->findOrFail($id);

		$series->delete();

		return redirect(route('admin.series.index', $series->id))
			->with(['flash.message' => 'Series deleted!',
					'flash.level'	=> 'success']);
	}

}

app/Http/Controllers/Api/SeriesController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class SeriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $series = \App\Series::get();

        return \Response::json(
          [
            'data' => [
              'series' => $series
            ]
          ]
        );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Frontend/SeriesController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class SeriesController extends Controller
{

  public function series($series_slug) {
    $series = \App\Series::with(['episodes' => function($query){
        $query->visible()->recent();
      }])
      ->visible()
      ->where('slug', '=', $series_slug)
      ->firstOrFail();

    // return $series;
    return view('frontend.series.landing', ['series' => $series]);
  }

  public function seriesSubslug($series_slug) {
    return redirect("/{$series_slug}");
  }

  public function seriesList() {
    $series = \App\Series::visible()->get();

    return view('frontend.series.list', ['series' => $series]);
  }

}

resources/views/admin/series/_form.blade.php
<div class="columns large-18">

	<!-- Series Core -->
	<div class="panel">
		<div class="row">

		<div class="columns large-24">
			<h3>Series Core</h3>
		</div>

		<div class="columns large-24">
			<label>Series Name
				{!! Form::text('name', null) !!}
			</label>
		</div>

		<div class="columns large-24">
			<label>Series Slug
				{!! Form::text('slug', null) !!}
			</label>
		</div>

		<div class="columns large-24">
			<label>Series Long Slug
				{!! Form::text('long_slug', null) !!}
			</label>
		</div>

		<div class="columns large-24">
			<label>Series Description
				{!! Form::textarea('description', null) !!}
			</label>
		</div>

		<div class="columns large-8 text-center">
			<label>Series Hidden
				{!! Form::checkbox('hidden') !!}
			</label>
		</div>
		<div class="columns large-8 text-center">
			<label>Series Retired
				{!! Form::checkbox('retired') !!}
			</label>
		</div>
		<div class="columns large-8 text-center">
			<label>Series Hiatus
				{!! Form::checkbox('hiatus') !!}
			</label>
		</div>

		</div>

	</div>

	<!-- Series Defaults, including art and people? -->
	<div class="panel">
		<div class="row">

		<div class="columns large-24">
			<h3>Series Album Art</h3> {{-- fart[album_art_id] --}}
			{!! Form::select('art_list[]',
				 [null => 'None'] + \App\AlbumArt::getArtList()->lists('name', 'id')->toArray(), null)
			!!}
			<p>This will be the default album art for episodes in this series. Changing this after an episode is saved will not change that episode's art.</p>
		</div>

		</div>
	</div>

	<div class="panel">
		<div class="row">

			<div class="columns large-24">
				<h3>Series Hosts</h3>
				{!! Form::select('people_default[]',
					 \App\Person::getPeopleList()->lists('name', 'id')->toArray(), null, ['multiple'])
				!!}
				<p>Select the default hosts for this series. Changing this after an episode is saved will not change that episode's party.</p>
			</div>

		</div>
	</div>

	<!-- Series Meta -->
	<div class="panel">
		<div class="row">

		<div class="columns large-24">
			<h3>Series Meta</h3>
		</div>

		<fieldset>
			<legend>Content</legend>

			<div class="columns large-24">
				<label>Landing Content
					{!! Form::text('meta[landing_content]') !!}
				</label>
				<p class="help-text">Add additional landing page (e.g. ~/series/) specific content.</p>
			</div>

			<div class="columns large-24">
				<label>Attribution Content
					{!! Form::text('meta[attribution_content]') !!}
				</label>
				<p class="help-text">Add additional global attribution content, useful for describing assets used for a series.</p>
			</div>

		</fieldset>

		<fieldset>
			<legend>Feed</legend>

		<div class="columns large-24">
			<label>Feed Author
				{!! Form::text('meta[feed_author]', null) !!}
			</label>
			{{-- <p class="help-text">Usually, <em>The Nexus</em>.</p> --}}
		</div>

		<div class="columns large-24">
			<label>Geographic Location
				{!! Form::text('meta[feed_geographic_location]', null) !!}
			</label>
		</div>

		<div class="columns large-24">
			<label>Episode Frequency
				{!! Form::text('meta[feed_episode_frequency]', null) !!}
			</label>
		</div>

		<div class="columns large-24">
			<label>Feed Tracking URL
				{!! Form::text('meta[feed_tracking_url]', null) !!}
			</label>
			<p class="help-text">Usually this is a link to a Podtrac or similar service's URL that ends in <em>mp3</em>.</p>
		</div>

		<div class="columns large-24">
			<label>Feed Image URL
				{!! Form::text('meta[feed_image_url]', null) !!}
			</label>
			<p class="help-text">A generic large album art image, usually hosted on a CDN.</p>
		</div>

		</fieldset>

		<fieldset>
			<legend>Google Play</legend>

			<div class="columns large-24">
				<label>Feed Tracking URL
					{!! Form::text('meta[google_play_subscription_url]', null) !!}
				</label>
			</div>


		</fieldset>

		<fieldset>
			<legend>iTunes</legend>

		<div class="columns large-24">
			<label>iTunes Subscription URL
				{!! Form::text('meta[itunes_subscription_url]', null) !!}
			</label>
		</div>

		<div class="columns large-24">
			<label>iTunes Summary
				{!! Form::textarea('meta[itunes_summary]', null) !!}
			</label>
		</div>

		<div class="columns large-24">
			<label>iTunes Keywords
				{!! Form::text('meta[itunes_keywords]', null) !!}
			</label>
		</div>

		<div class="columns large-24">
			<label>iTunes Category Primary
				{!! Form::text('meta[itunes_category_primary]', null) !!}
			</label>
		</div>

		<div class="columns large-24">
			<label>iTunes Category Secondary
				{!! Form::text('meta[itunes_category_secondary]', null) !!}
			</label>
		</div>

		<div class="columns large-24">
			<label>iTunes Email
				{!! Form::text('meta[itunes_email]', null) !!}
			</label>
		</div>

		<div class="columns large-24">
			<label>iTunes Explicit
				{!! Form::checkbox('meta[itunes_explicit]', null) !!}
			</label>
		</div>

		<div class="columns large-24">
			<label>iTunes Image URL
				{!! Form::checkbox('meta[itunes_image_url]', null) !!}
			</label>
			<p class="help-text">A large generic album art image, usually hosted on a CDN, meeting the iTunes specifications for album art.</p>
		</div>

		</fieldset>

		</div>
	</div>

</div><!-- end column for series -->


<div class="columns large-6">
	<div class="panel">
		{!! Form::submit('Save', ['class' => 'button expand']) !!}
	</div>
</div>

resources/views/admin/series/create.blade.php
@extends('admin.admin')

@section('content')

<div class="row">
	{!! Form::model($series, ['method' => 'POST', 'action' => ['Admin\SeriesController@store']]) !!}

	@include ('admin.series._form')

	{!! Form::close() !!}
</div>


@endsection

resources/views/admin/series/edit.blade.php
@extends('admin.admin')

@section('content')

<div class="row">
	{!! Form::model($series, ['method' => 'PATCH', 'action' => ['Admin\SeriesController@update', $series->id]]) !!}

	@include ('admin.series._form')

	{!! Form::close() !!}
</div>


@endsection

resources/views/admin/series/index.blade.php
@extends('admin.admin')

@section('content')

<div class="row">

<div class="page-navigation">
	<dl class="sub-nav">
	  <dt>Series:</dt>
	  <dd><a href="/admin/series/create">New Series</a></dd>
	</dl>
</div>

<div class="columns large-24">
		<table>
			<thead>
				<tr>
					<th>Series</th>
					<th>Slug</th>
					<th>Description</th>
					<th>Created</th>
				</tr>
			</thead>

			<tbody>
				@foreach ($series as $serie)
				<tr>
					<td class="text-center"><span class="title" title="{{ $serie->id }}">{{ $serie->name }}</span></td>
					<td class="text-center">
						<span class="short slug">{{$serie->slug}}</span>
						<br />
						<span title="long slug">{{$serie->long_slug}}</span>
					</td>
					<td>
						<p>{{ $serie->description }}</p>
						<ul class="button-group list-actions">

							<li><a class="button tiny secondary" href="{{ route('series', $serie->slug) }}">View</a></li>
							<li><a class="button tiny secondary" href="{{ route('admin.series.edit', $serie->id) }}">Edit</a></li>
							<li>
								{{-- <a class="button tiny warning" data-delete="true" href="{{ route('admin.series.destroy', $serie->id) }}">Delete</a> --}}
							</li>

						</ul>
					</td>
					<td>{{ $serie->created_at->format('F j, Y') }}</td>
				</tr>
				@endforeach
			</tbody>

		</table>
</div>

</div>


@endsection