app/Http/routes.php
<?php

$router->pattern('series_slug', '[A-Za-z-]+');
$router->pattern('person_slug', '[A-Za-z-]+');

$router->pattern('episode_number', '\d+');

Route::group(['middleware' => ['web']], function () {

    Route::auth();

    Route::group(['prefix' => 'api', 'middleware' => 'auth'], function(){

    	Route::resource('people', 'Api\PeopleController');
    	Route::resource('series', 'Api\SeriesController');
    	Route::resource('episodes', 'Api\EpisodeController');
    	Route::resource('art', 'Api\AlbumArtController');

    	Route::get('media/check', ['as' => 'media-check', 'uses' => 'Api\MediaController@check']);
    });

    Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function(){

    	Route::get('dashboard', ['as' => 'dashboard', 'uses' => 'Admin\DashboardController@index']);

    	Route::resource('series', 'Admin\SeriesController');

    	Route::resource('episodes', 'Admin\EpisodeController');

    	Route::resource('art', 'Admin\ArtController');

    	Route::resource('people', 'Admin\PeopleController');

    	Route::group(['prefix' => 'ajax'], function(){

    		Route::get('people/search/', 'Admin\AjaxController@peopleSearch');
    		Route::get('people/initial/', 'Admin\AjaxController@people');

    		Route::get('episode/related/search/', 'Admin\AjaxController@episodesSearch');
    		Route::get('episode/related/initial/', 'Admin\AjaxController@episodes');

    		Route::get('media/initial/', 'Admin\AjaxController@mediaInitial');
    		Route::get('media/check/', 'Admin\AjaxController@mediaCheck');

    		Route::post('art/upload/', 'Admin\ArtController@upload');
    	});

    });

    /**
     * Root routes.
     *
     * Routes that are attached to the /
     * - home
     * - latest
     * - admin shortcut
     */

    Route::get('admin', [
      'uses' => 'Frontend\RootController@admin'
    ]);

    Route::get('/', [
      'as' => 'home',
      'uses' => 'Frontend\RootController@home'
    ]);

    Route::get('/latest', [
      'as' => 'latest',
      'uses' => 'Frontend\RootController@latest'
    ]);

    /**
     * People routes.
     *
     * - people's full list
     * - a person's page
     */

    Route::get('/people/', [
      'as' => 'people',
      'uses' => 'Frontend\PeopleController@people'
    ]);

    Route::get('/person/{person_slug}/', [
      'as' => 'person',
      'uses' => 'Frontend\PeopleController@person'
    ]);

    /**
     * Episode routes.
     *
     * Most of these routes are functionally redirects.
     *
     * - /episode/{s}{n}; legacy format
     * - /e/{id}; shortcut format
     * - /{s}{n}; legacy shortcut format
     * - /{s}/{n}; new format (that everyone loves)
     */

    Route::get('/episode/{series_slug}{episode_number}', [
      'uses' => 'Frontend\EpisodesController@episodeLegacyRedirect'
    ]);

    Route::get('/e/{id}', [
      'uses' => 'Frontend\EpisodesController@episodeByIdRedirect'
    ]);

    Route::get('/{series_slug}{episode_number}/', [
      'uses' => 'Frontend\EpisodesController@episodeLegacyRedirect'
    ]);

    Route::get('/{series_slug}/{episode_number}/', [
      'as' => 'episode',
      'uses' => 'Frontend\EpisodesController@episode'
    ]);

    /**
     * Series routes.
     *
     * - series list
     * - single series (redirect)
     * - single series
     */

    Route::get('/series', [
      'as' => 'series-list',
      'uses' => 'Frontend\SeriesController@seriesList'
    ]);

    Route::get('/series/{series_slug}', [
      'as' => 'series',
      'uses' => 'Frontend\SeriesController@seriesSubslug'
    ]);

    Route::get('/{series_slug}/', [
      'as' => 'series',
      'uses' => 'Frontend\SeriesController@series'
    ]);

    Route::get('/master/feed', [
      'as' => 'master.feed',
      'uses' => 'Frontend\FeedsController@feedMaster'
    ]);

    /**
     * Route for series/feed.
     *
     * This route fetches the published episodes without fringes
     * of the specified episode.
     */
    Route::get('/{series_slug}/feed', [
      'as' => 'series.feed',
      'uses' => 'Frontend\FeedsController@feedGeneral'
    ]);

    /**
     * Route for series/feed/fringe.
     *
     * This route gets the latest episodes and their fringes if they are available,
     * and merges them into a single collection for the feed.
     *
     * TODO: fix this awful query mess
     * TODO: really, why haven't you fixed this yet?
     */
    Route::get('/{series_slug}/feed/fringe', [
      'as' => 'series.feed.fringe',
      'uses' => 'Frontend\FeedsController@feedFringe'
    ]);

});

app/Person.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class Person extends Model {

	protected $guarded = [];

	protected $table = 'people';

	public function episodes() {
		return $this->belongsToMany('App\Episode', 'people_episodes', 'person_id', 'episode_id');
	}

	public function series() {
		return $this->belongsToMany('App\Series', 'people_series', 'person_id', 'series_id');
	}

	public function scopeVisible($query) {
		return $query->where('hidden', '=', false);
	}

	public static function getPeopleList() {
		return self::orderBy('name', 'asc')->get();
	}

}

app/Http/Controllers/Admin/PeopleController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class PeopleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
      $people = \App\Person::orderBy('created_at', 'desc')->get();

      return view('admin.people.index', ['people' => $people]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {

        return view('admin.people.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
      $input = $request->all();

      $person = \App\Person::create($input);

      $person->save();

      return redirect(route('admin.people.edit', $person->id))
          ->with(['flash.message' => 'Person updated!',
              'flash.level'	=> 'success']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
      $person = \App\Person::findOrFail($id);

      return view('admin.people.edit', ['person' => $person]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $input = $request->all();

        $person = \App\Person::findOrFail($id);

      	$person->update($input);

        return redirect(route('admin.people.edit', $person->id))
    				->with(['flash.message' => 'Person updated!',
    						'flash.level'	=> 'success']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
      $person = \App\Person::findOrFail($id);

      $person->delete();

      return redirect(route('admin.people.index'))
        ->with(['flash.message' => 'Person deleted!',
            'flash.level'	=> 'success']);
    }
}

app/Http/Controllers/Api/PeopleController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class PeopleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $query = $request->input('q');

        if ($query) {
          $people = \App\Person::where('name', 'LIKE', "%$query%")->take(10)->get();
        } else {
          $people = \App\Person::get();
        }

        return \Response::json(
          [
            'data' => [
              'people' => $people
            ]
          ]
        );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Frontend/PeopleController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class PeopleController extends Controller
{

  public function person() {
    $person = \App\Person::visible()
    ->where('slug', '=', $person_slug)
    ->firstOrFail();

    return $person;
  }

  public function people()
  {
    $people = \App\Person::visible()
      ->paginate(15);

    return $people;
  }

}

resources/views/admin/people/_form.blade.php
<div class="columns large-18">

	<!-- Series Core -->
	<div class="panel">
		<div class="row">

			<div class="columns large-24">
				<h3>Person</h3>
			</div>

			<div class="columns large-24">
				<label>Person Name
					{!! Form::text('name') !!}
				</label>
			</div>

			<div class="columns large-24">
				<label>Person Slug
					{!! Form::text('slug') !!}
				</label>
			</div>

			<div class="columns large-24">
				<label>Person Email
					{!! Form::email('email') !!}
				</label>
			</div>

			<div class="columns large-24">
				<label>Person Description
					{!! Form::textarea('content') !!}
				</label>
			</div>

			<div class="columns large-24 text-center">
				<label>Person Hidden
					{!! Form::checkbox('hidden') !!}
				</label>
			</div>

			<div class="columns large-24">
				<label>Web URL
					{!! Form::text('web_url') !!}
				</label>
			</div>

			<div class="columns large-24">
				<label>Twitter URL
					{!! Form::text('twitter_url') !!}
				</label>
			</div>

			<div class="columns large-24">
				<label>Social URL
					{!! Form::text('social_url') !!}
				</label>
			</div>

		</div>
	</div>

</div><!-- end column for series -->


<div class="columns large-6">
	<div class="panel">
		{!! Form::submit('Save', ['class' => 'button expand']) !!}
	</div>
</div>

resources/views/admin/people/create.blade.php
@extends('admin.admin')

@section('content')

<div class="row">
	{!! Form::open(['action' => ['Admin\PeopleController@store']]) !!}

	@include ('admin.people._form')

	{!! Form::close() !!}
</div>


@endsection

resources/views/admin/people/edit.blade.php
@extends('admin.admin')

@section('content')

<div class="row">
	{!! Form::model($person, ['method' => 'PATCH', 'action' => ['Admin\PeopleController@update', $person->id]]) !!}

	@include ('admin.people._form')

	{!! Form::close() !!}
</div>


@endsection

resources/views/admin/people/index.blade.php
@extends('admin.admin')

@section('content')


<div class="row">

<div class="page-navigation">
	<dl class="sub-nav">
	  <dt>Episodes:</dt>
	  <dd><a href="/admin/people/create">New Person</a></dd>
	</dl>
</div>

<div class="columns large-24">

	<table class="full">
		<thead>
			<tr>
				<th>Name</th>
				<th>Created</th>
			</tr>
		</thead>

		<tbody>
			@foreach ($people as $person)
			<tr>
				<td>
					<span class="name" title="{{ $person->id }}"><a href="{{ route('admin.people.edit', $person->id) }}">{{ $person->name }}</a></span>

					<ul class="button-group list-actions">

					<li><a class="button tiny secondary" href="{{ route('admin.people.edit', $person->id) }}">Edit</a></li>
					<li>
						<a class="button tiny warning" data-delete="true" href="{{ route('admin.people.destroy', $person->id) }}">Delete</a>
						{{-- delete button supported by javascript --}}
					</li>

				</ul>

				</td>
				<td class="text-center">{{ $person->created_at->format('F j, Y') }}</td>
			</tr>
			@endforeach
		</tbody>

	</table>


</div>


</div>


@endsection