app/Http/routes.php
<?php

$router->pattern('series_slug', '[A-Za-z-]+');
$router->pattern('person_slug', '[A-Za-z-]+');

$router->pattern('episode_number', '\d+');

Route::group(['middleware' => ['web']], function () {

    Route::auth();

    Route::group(['prefix' => 'api', 'middleware' => 'auth'], function(){

    	Route::resource('people', 'Api\PeopleController');
    	Route::resource('series', 'Api\SeriesController');
    	Route::resource('episodes', 'Api\EpisodeController');
    	Route::resource('art', 'Api\AlbumArtController');

    	Route::get('media/check', ['as' => 'media-check', 'uses' => 'Api\MediaController@check']);
    });

    Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function(){

    	Route::get('dashboard', ['as' => 'dashboard', 'uses' => 'Admin\DashboardController@index']);

    	Route::resource('series', 'Admin\SeriesController');

    	Route::resource('episodes', 'Admin\EpisodeController');

    	Route::resource('art', 'Admin\ArtController');

    	Route::resource('people', 'Admin\PeopleController');

    	Route::group(['prefix' => 'ajax'], function(){

    		Route::get('people/search/', 'Admin\AjaxController@peopleSearch');
    		Route::get('people/initial/', 'Admin\AjaxController@people');

    		Route::get('episode/related/search/', 'Admin\AjaxController@episodesSearch');
    		Route::get('episode/related/initial/', 'Admin\AjaxController@episodes');

    		Route::get('media/initial/', 'Admin\AjaxController@mediaInitial');
    		Route::get('media/check/', 'Admin\AjaxController@mediaCheck');

    		Route::post('art/upload/', 'Admin\ArtController@upload');
    	});

    });

    /**
     * Root routes.
     *
     * Routes that are attached to the /
     * - home
     * - latest
     * - admin shortcut
     */

    Route::get('admin', [
      'uses' => 'Frontend\RootController@admin'
    ]);

    Route::get('/', [
      'as' => 'home',
      'uses' => 'Frontend\RootController@home'
    ]);

    Route::get('/latest', [
      'as' => 'latest',
      'uses' => 'Frontend\RootController@latest'
    ]);

    /**
     * People routes.
     *
     * - people's full list
     * - a person's page
     */

    Route::get('/people/', [
      'as' => 'people',
      'uses' => 'Frontend\PeopleController@people'
    ]);

    Route::get('/person/{person_slug}/', [
      'as' => 'person',
      'uses' => 'Frontend\PeopleController@person'
    ]);

    /**
     * Episode routes.
     *
     * Most of these routes are functionally redirects.
     *
     * - /episode/{s}{n}; legacy format
     * - /e/{id}; shortcut format
     * - /{s}{n}; legacy shortcut format
     * - /{s}/{n}; new format (that everyone loves)
     */

    Route::get('/episode/{series_slug}{episode_number}', [
      'uses' => 'Frontend\EpisodesController@episodeLegacyRedirect'
    ]);

    Route::get('/e/{id}', [
      'uses' => 'Frontend\EpisodesController@episodeByIdRedirect'
    ]);

    Route::get('/{series_slug}{episode_number}/', [
      'uses' => 'Frontend\EpisodesController@episodeLegacyRedirect'
    ]);

    Route::get('/{series_slug}/{episode_number}/', [
      'as' => 'episode',
      'uses' => 'Frontend\EpisodesController@episode'
    ]);

    /**
     * Series routes.
     *
     * - series list
     * - single series (redirect)
     * - single series
     */

    Route::get('/series', [
      'as' => 'series-list',
      'uses' => 'Frontend\SeriesController@seriesList'
    ]);

    Route::get('/series/{series_slug}', [
      'as' => 'series',
      'uses' => 'Frontend\SeriesController@seriesSubslug'
    ]);

    Route::get('/{series_slug}/', [
      'as' => 'series',
      'uses' => 'Frontend\SeriesController@series'
    ]);

    Route::get('/master/feed', [
      'as' => 'master.feed',
      'uses' => 'Frontend\FeedsController@feedMaster'
    ]);

    /**
     * Route for series/feed.
     *
     * This route fetches the published episodes without fringes
     * of the specified episode.
     */
    Route::get('/{series_slug}/feed', [
      'as' => 'series.feed',
      'uses' => 'Frontend\FeedsController@feedGeneral'
    ]);

    /**
     * Route for series/feed/fringe.
     *
     * This route gets the latest episodes and their fringes if they are available,
     * and merges them into a single collection for the feed.
     *
     * TODO: fix this awful query mess
     * TODO: really, why haven't you fixed this yet?
     */
    Route::get('/{series_slug}/feed/fringe', [
      'as' => 'series.feed.fringe',
      'uses' => 'Frontend\FeedsController@feedFringe'
    ]);

});

app/Http/Controllers/Admin/EpisodeController.php
<?php namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Helpers\FormComponentVerifier as ComponentVerifier;

class EpisodeController extends Controller {

	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct()
	{
		$this->middleware('auth');
	}

	private function getRequestInput(Request $request) {
		$except = [
			'components-activated',
			'art'
		];
		return $request->except($except);
	}

	public function index() {
		$episodes = \App\Episode::orderBy('created_at', 'DESC')->paginate(20);
		$series = \App\Series::orderBy('name', 'DESC')->get();

		return view('admin.episodes.index', [
			'episodes' => $episodes,
			'series' => $series
		]);
	}

	public function show($id) {
		return redirect(route('admin.episodes.index'));
	}

	public function create() {
		// $series = \App\Series::usable()->lists('name', 'id');
		//
		// $array = ['series' => $series];
		// return view('admin.episodes.create', $array);
		return view('admin.episodes.create');
	}

	public function store(Request $request, ComponentVerifier $verifier) {

		$input = $this->getRequestInput($request);

		$this->_validate($request);

		$episode = \App\Episode::create($input);

		$episode->save();

		$this->saveComponents($episode, $request, $verifier);

		$this->saveArt($episode, $request);

		return redirect(route('admin.episodes.edit', $episode->id))
		->with(['flash.message' => 'Episode created!',
				'flash.level'	=> 'success']);
	}

	public function edit($id) {

		$episode = \App\Episode::with(['series', 'media'])->findOrFail($id);

		$series = \App\Series::usable()->lists('name', 'id');

		$array = ['series' => $series, 'episode' => $episode];
		return view('admin.episodes.edit', $array);

	}

	public function update(Request $request, ComponentVerifier $verifier, $id) {

		$input = $this->getRequestInput($request);

		$this->_validate($request);

		$episode = \App\Episode::findOrFail($id);

		$episode->update($input);

		$this->saveComponents($episode, $request, $verifier);

		$this->saveArt($episode, $request);

		return redirect(route('admin.episodes.edit', $episode->id))
		->with(['flash.message' => 'Episode updated!',
				'flash.level'	=> 'success']);
	}

	private function saveComponents(\App\Episode $episode, Request $request, ComponentVerifier $verifier) {
		if ($verifier->verify($request, 'people')) {
			$people = $request->input('people', []);
			$episode->people()->sync($people);
		}

		if ($verifier->verify($request, 'related')) {
			$related = $request->input('related', []);
			$episode->related()->sync($related);
		}

		if ($verifier->verify($request, 'media')) {
			$media = $request->input('media', []);
			// this method is on the controller and not elsewhere
			// because it processes the form structure more specifically than would be required
			// if the media was being saved manually
			$this->saveMedia($episode, $media);
		}
	}

	private function saveArt($episode, $request) {
		$art = $request->input('art');
		if (!empty($art['album_art_id'])) {
			$episode->art()->sync([$art['album_art_id']]);
		}
	}

	private function saveMedia($episode, $media) {

		// media id accumulator, used for syncing existing and deleted media
		$mediaIds = [];

		// iterate througth the media just sent up on this request
		foreach ($media as $data) {
			$id = array_get($data, 'id');

			// fields that should not be here are ignored through Model::guarded

			if ($id) {
				$episodeMedia = \App\EpisodeMedia::find($id);
				// the suggested id was invalid, so skip this iteration
				if ($episodeMedia == null) {
					continue;
				}
				$episodeMedia->update($data);
				$mediaIds[] = $id;
			} else {
				// the item does not have an id field, so it must be a new entry
				$episodeMedia = new \App\EpisodeMedia($data);
				$mediaIds[] = $episodeMedia->id;
			}

			// save the media to this episode
			$episode->media()->save($episodeMedia);

		}

		// using the accumulated ids, remove the ids that were not involved in this transaction
		$episode->media()->whereNotIn('id', $mediaIds)->delete();
	}

	private function _validate(Request $request) {
		$this->validate($request, [
			'name' => 'required|min:2|max:140',
			'series_id' => 'required|integer',
			'number' => 'required|integer',
			'description' => 'max:300'
		]);
	}

	public function destroy(Request $request, $id) {

		$episode = \App\Episode::findOrFail($id);

		$episode->delete();

		return redirect(route('admin.episodes.index', $episode->id))
		->with(['flash.message' => 'Episode deleted!',
				'flash.level'	=> 'success']);

	}

}

app/Http/Controllers/Api/EpisodeController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Episode as Episode;

class EpisodeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
      $query = $request->input('q');

      if ($query) {
        $episodes = \App\Episode::where('title', 'LIKE', "%$query%")->take(10)->orderBy('id', 'desc')->get();
      } else {
        $episodes = \App\Episode::orderBy('id', 'desc')->get();
      }

      return \Response::json(
        [
          'data' => [
            'episodes' => $episodes
          ]
        ]
      );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

      $input = $request->input('episode');
      $relationships = ['art', 'series', 'people', 'related', 'media'];
      $core = array_except($input, $relationships);


      $episode = Episode::create($core);

      $episode->save();

      $episode = $this->saveRelated($episode, $request);

      // fetch a clean object and return it

      $e = Episode::with($relationships)->find($episode->id);

      return \Response::json(
        [
          'data' => [
            'episode' => $e->toArray()
          ],
          'method' => 'create'
        ]
      );

    }


    private function saveRelated(Episode $episode, Request $request) {
      $episode->people()->sync($request->input('episode.people', []), !$episode->wasRecentlyCreated);

      $episode->related()->sync($request->input('episode.related', []));

      $this->saveMedia($episode, $request->input('episode.media', []));

      return $episode;
    }



    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $episode = \App\Episode::with(['series', 'people', 'related', 'media', 'art'])->findOrFail($id);

      return \Response::json(
        [
          'data' => [
            'episode' => $episode
          ],
          'method' => 'show'
        ]
      );
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $input = $request->input('episode');
      $relationships = ['art', 'series', 'people', 'related', 'media'];
      $core = array_except($input, $relationships);

      if (empty($core['album_art_id'])) {
        $core['album_art_id'] = null;
      }

      $episode = Episode::findOrFail($id);

      $episode->update($core);

      $this->saveRelated($episode, $request);

      // fetch a clean object and return it

      $e = Episode::with($relationships)->find($episode->id);

      return \Response::json(
        [
          'data' => [
            'episode' => $e->toArray()
          ],
          'method' => 'update'
        ]
      );
    }

    private function saveMedia(Episode $episode, $media) {
  		// media id accumulator, used for syncing existing and deleted media
  		$mediaIds = [];

  		// iterate througth the media just sent up on this request
  		foreach ($media as $data) {
  			$id = array_get($data, 'id');

  			// fields that should not be here are ignored through Model::guarded

  			if ($id) {
  				$episodeMedia = \App\EpisodeMedia::find($id);
  				// the suggested id was invalid, so skip this iteration
  				if ($episodeMedia == null) {
  					continue;
  				}
  				$episodeMedia->update($data);
  				$mediaIds[] = $id;
  			} else {
  				// the item does not have an id field, so it must be a new entry
  				$episodeMedia = new \App\EpisodeMedia($data);
  				$mediaIds[] = $episodeMedia->id;
  			}

  			// save the media to this episode
  			$episode->media()->save($episodeMedia);

  		}

  		// using the accumulated ids, remove the ids that were not involved in this transaction
  		$episode->media()->whereNotIn('id', $mediaIds)->delete();
  	}

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Frontend/EpisodesController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class EpisodesController extends Controller
{

  public function episode($series_slug, $episode_number) {
    $episode = \App\Episode::with(['series', 'people', 'related', 'art', 'media'])
      ->accessible()
      ->withSlug($series_slug)
      ->where('number', '=', $episode_number)
      ->firstOrFail();

    // return $episode;
    return view('frontend.episode.landing', ['episode' => $episode]);
  }

  public function episodeLegacyRedirect($series_slug, $episode_number) {
    return redirect("$series_slug/$episode_number");
  }

  public function episodeByIdRedirect($id) {
    $episode = \App\Episode::with(['series'])
      ->where('id', '=', $id)
      ->firstOrFail();
    $number = $episode->number;
    $series_slug = $episode->series->slug;
    return redirect("$series_slug/$number");
  }

}

resources/views/admin/episodes/__form.blade.php
<div class="columns large-18">

	<div class="panel">
		<div class="row">

		<div class="columns large-24">
			<h3>Episode</h3>
		</div>

		<div class="columns large-24">
			<label>Episode Name
				{!! Form::text('name', null) !!}
			</label>
		</div>

		<div class="columns large-24">
			<label>Episode Series
				{!! Form::select('series_id', $series) !!}
			</label>
		</div>

		<div class="columns large-24">
			<label>Episode Number
				{!! Form::input('number', 'number') !!}
			</label>
		</div>

		<div class="columns large-24">
			<label>Episode Content
				{!! Form::textarea('content', null, ['rows' => 20, 'class' => 'content-field']) !!}
			</label>
		</div>

		<div class="columns large-24">
			<label>Episode Description
				{!! Form::textarea('description', null, ['rows' => 4]) !!}
			</label>
		</div>


		<div class="columns large-12 text-center">
			<label>Hidden
				{!! Form::checkbox('hidden') !!}
			</label>
		</div>
		<div class="columns large-12 text-center">
			<label>NSFW
				{!! Form::checkbox('nsfw') !!}
			</label>
		</div>


		</div>
	</div>

	<div class="panel">
		<div class="row">

		<div class="columns large-24">
			<h3>People</h3>

			<div class="people-container" data-id="{{ $episode->id or -1 }}"></div>

		</div>

		</div>
	</div>

	<div class="panel">
		<div class="row">

			<div class="columns large-24">
				<h3>Related</h3>

				<div class="related-container" data-id="{{ $episode->id or -1 }}"></div>

			</div>

		</div>
	</div>

	<div class="panel">
		<div class="row">

		<div class="columns large-24">
			<h3>Media</h3>

			<div class="media-container" data-id="{{ $episode->id or -1 }}">

			</div>

		</div>

		</div>
	</div>

	<div class="panel">
		<div class="row">

		<div class="columns large-24">
			<h3>Art</h3>

			{!! Form::select('art[album_art_id]',
				   [null => 'Series Default'] + \App\AlbumArt::getArtList()->lists('name', 'id')->toArray(),
				   isset($episode) ? $episode->art->lists('id')->toArray() : [])
			!!}


		</div>

		</div>
	</div>

</div>


<div class="columns large-6">
	<div class="panel">

		{{-- <div class="columns large-24"> --}}
			<label>Episode State
				{!! Form::select('state', array_map(
						function($i){return ucfirst($i);},
						Config::get('nexus.episode.states'))
						)
				!!}
			</label>
		{{-- </div> --}}

		{!! Form::submit('Save', ['class' => 'button expand']) !!}


	</div>
</div>

resources/views/admin/episodes/_create.blade.php
@extends('admin.admin')

@section('content')

<div class="row">
	{!! Form::open(['action' => ['Admin\EpisodeController@store']]) !!}

	@include ('admin.episodes._form')

	{!! Form::close() !!}
</div>


@endsection

resources/views/admin/episodes/_edit.blade.php
@extends('admin.admin')

@section('content')

<div class="row">
	{!! Form::model($episode, ['method' => 'PATCH', 'action' => ['Admin\EpisodeController@update', $episode->id]]) !!}

	@include ('admin.episodes._form')

	{!! Form::close() !!}
</div>


@endsection

resources/views/admin/episodes/_form.blade.php
	<div class="columns large-18">

		<div class="panel">
			<div class="row">

				<div class="columns large-24">
					<h3>Episode</h3>
				</div>

				<div class="columns large-24">
					<label>Title:
						<input type="text" v-model="episode.title">
					</label>
				</div>

				<div class="columns large-24" v-show="episode.title">
					<label>Subtitle:
						<input type="text" v-model="episode.subtitle">
					</label>
				</div>

				<div class="columns large-24">
					<label>Series:
						<select class="form-control"
						v-model="episode.series_id"
						>
							<option value="">Select a series</option>
							<option v-for="s in series" v-bind:value="s.value">@{{s.text}}</option>
						</select>
					</label>
				</div>

				<div class="columns large-24">
					<label>Number:
						<input type="number" v-model="episode.number">
					</label>
				</div>

				<div class="columns large-24">
					<label>Content:
						<textarea v-model="episode.content" rows="12" cols="40"></textarea>
					</label>
				</div>

				<div class="columns large-24">
					<label>Description:
						<textarea v-model="episode.description" rows="3" cols="40"></textarea>
					</label>
					<p class="help-text">Try to limit the episode description to 160 characters.</p>
				</div>

				<div class="columns medium-8 text-center">
					<label>Hidden
						<input type="checkbox" v-model="episode.hidden">
					</label>
					<p class="help-text">When an episode is <em>hidden</em>, it will not be visible or accessible from the front end.</p>
				</div>
				<div class="columns medium-8 text-center">
					<label>NSFW
						<input type="checkbox" v-model="episode.nsfw">
					</label>
					<p class="help-text">When an episode is <em>NSFW</em>, it will be shown as such on its episode page.</p>
				</div>
				<div class="columns medium-8 text-center">
					<label>Unlisted
						<input type="checkbox" v-model="episode.unlisted">
					</label>
					<p class="help-text">
						When an episode is <em>unlisted</em>, it is not listed on the front end, but is still directly accessible.
					</p>
				</div>

			</div>
		</div>

		<div class="panel">
			<div class="row">

				<div class="columns medium-24 text-center">
					<label>Debug
						<input type="checkbox" v-model="meta.debug">
					</label>
					<p class="help-text">Do you want to temporarily see the debug?</p>
				</div>

<div class="columns large-24" v-show="meta.debug">
<pre>
@{{ episode | json }}
</pre>
</div>

			</div>
		</div>

		<div class="panel">
			<div class="row">

			<div class="columns large-24">
				<h3>People</h3>

				<label>Add A Person</label>
				<input class="form-control" type="text" placeholder="Search for a person"
				v-el:peoplequery
				v-model="queries.people"
				>
				<ul class="no-bullet" v-if="episode.people.length > 0">
					<li class="list-group-item" v-for="person in episode.people" track-by="id">
				@{{person.name}}
						<select v-model="person.pivot.role">
							<option v-for="p in peopleRoles" v-bind:value="p.value">@{{p.text}}</option>
						</select>
						<button v-on:click="removePerson(person)" type="button" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					</li>
				</ul>
				<p class="help-text">If left blank, the default series hosts will be automatically added to this episode.</p>

			</div>

			</div>
		</div><!-- episode.people -->

		<div class="panel">
			<div class="row">

				<div class="columns large-24">

				<h4>Related</h4>

        <div class="form-group">
          <label>Parent:</label>
          <input class="form-control" type="text" placeholder="Select the parent episode"
            v-el:relatedparent
            v-model="queries.related.parent"
            v-bind:disabled="parents.length > 0"
          >
          <div v-if="parents.length > 0">
            <div v-for="parent in parents">
              @{{parent.name}} <button v-on:click="removeRelated(parent)" type="button" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
          </div>
        </div>

        <div class="form-group">
          <label>Fringe:</label>
          <input class="form-control" type="text" placeholder="Select the fringe episode"
            v-el:relatedfringe
            v-model="queries.related.fringe"
            v-bind:disabled="fringes.length > 0"
          >
          <div v-if="fringes.length > 0">
            <div v-for="fringe in fringes">
              @{{fringe.name}} <button v-on:click="removeRelated(fringe)" type="button" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
          </div>
        </div>

				</div>

			</div>
		</div><!-- episode.related -->

		<div class="panel">
			<div class="row">

				<div class="columns large-24">

					<h4>Media</h4>
					<div class="form-group">
						<a class="button" href="#" role="button"
							v-on:click="newMP3Media"
						>New MP3 Media</a>
					</div>

						<div class="row" v-for="media in episode.media">
							<div class="columns large-24">

								<label>@{{media.type | uppercase}}:</label>

								<div>
									<input type="text" v-model="media.url">
									<button type="button" class="btn btn-primary"
										v-on:click="checkMedia(media, $event)"
									>Update</button>
									<button v-on:click="removeMedia(media, $event)" type="button" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></button>
								</div>

								<div v-if="media.length && media.size">
									@{{media.length}} | @{{media.size}}
								</div>

							</div>
						</div>

				</div>

			</div>
		</div>

		<div class="panel">
			<div class="row">
				<div class="columns large-24">

					<h4>Album Art</h4>

					<select v-model="episode.album_art_id">
						<option :value="">Default</option>
						<option v-for="a in art" :value="a.value">@{{a.text}}</option>
					</select>
					<p class="help-text">Select specific album art for this episode, otherwise the default series album art will be used.</p>
				</div>
			</div>
		</div>

		<div class="panel">
			<div class="row">

				<div class="columns large-24">
					<h4>Other</h4>

					<label>Episode Notes:
						<textarea v-model="episode.notes" rows="5" cols="40"></textarea>
					</label>
					<p class="help-text">Private notes on this episode.</p>
				</div>

			</div>
		</div>

	</div><!-- all episode modules -->

	<div class="columns large-6">
		<div class="panel">

			<label>Episode State
				<select class="form-control"
				v-model="episode.state"
				>
					<option v-for="s in states" :value="s.value">@{{s.text}}</option>
				</select>
			</label>

			<input class="button expand" type="submit" :disabled="saveable == false" value="Save">

		</div>
	</div>

resources/views/admin/episodes/_media.blade.php
<div class="media">

	<div class="columns large-18">
		<label>
			Media Type
			{!! Form::select("media[{$media->id}][type]", array_map(
			function($i){return strtoupper($i);},
			Config::get('nexus.media.types')),
			$media->type
			)
	!!}
		</label>
	</div>

	<div class="columns large-24">
		<label>Media URL
			<div class="row collapse">
				<div class="small-20 columns">
					{!! Form::text("media[{$media->id}][url]", $media->url, ['class' => 'form-media-url']) !!}
				</div>
				<div class="small-4 columns">
					<a href="#" class="form-media-load button postfix action-load">Load</a>
				</div>
			</div>
		</label>
	</div>

	<div class="columns large-24">
		<ul class="inline-list hide">
			<li>
				Length: <span class="form-media-length-display"></span>
				<input class="form-media-length" type="hidden" />
			</li>
			<li>
				Size: <span class="form-media-size-display"></span>
			</li>
			<li>
				Type: <span class="form-media-type-display"></span>
			</li>
			<li>
				MIME: <span class="form-media-mime-display"></span>
			</li>
			<li>

			</li>
		</ul>
	</div>

	<div class="columns large-24">
		<button class="action-delete button tiny secondary right">&times;</button>
	</div>


</div>

resources/views/admin/episodes/create.blade.php
@extends('admin.admin')

@section('content')


<episode data-id="{{ null }}">

</episode>

@endsection

resources/views/admin/episodes/edit.blade.php
@extends('admin.admin')

@section('content')

<episode data-id="{{ $episode->id }}">

</episode>

@endsection

resources/views/admin/episodes/index.blade.php
@extends('admin.admin')

@section('content')

<div class="row">

<div class="page-navigation">
	<dl class="sub-nav">
	  <dt>Episodes:</dt>
	  <dd><a href="/admin/episodes/create">New Episode</a></dd>
	</dl>
</div>

<div class="columns large-24">

	<div class="pagination-centered">
		{!! $episodes->render(); !!}
	</div>

	<table class="full">
		<thead>
			<tr>
				<th>Title</th>
				<th>Series</th>
				<th>Created</th>
				<th>Status</th>
			</tr>
		</thead>

		<tbody>
			@foreach ($episodes as $episode)
			<tr>
				<td>
					<span class="title" title="{{ $episode->id }}"><a href="{{ route('admin.episodes.edit', $episode->id) }}">{{ $episode->formal_title }}</a></span>
						<ul class="button-group list-actions">

						<li><a class="button tiny secondary" href="{{ route('admin.episodes.edit', $episode->id) }}">Edit</a></li>
						<li><a class="button tiny secondary" href="{{ route('episode', [$episode->series->slug, $episode->number]) }}">View</a></li>
						<li>
							<a class="button tiny warning" data-delete="true" href="{{ route('admin.episodes.destroy', $episode->id) }}">Delete</a>
							{{-- delete button supported by javascript --}}
						</li>

					</ul>
				</td>
				<td class="text-center">{{ $episode->series->name }}</td>
				<td class="text-center">{{ $episode->created_at->format('F j, Y') }}</td>
				<td class="text-center">{{ ucfirst($episode->state) }}</td>
			</tr>
			@endforeach
		</tbody>

	</table>

	<div class="pagination-centered">
		{!! $episodes->render(); !!}
	</div>

</div>


</div>


@endsection